# Generated by Django 5.0.7 on 2024-10-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_eyeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='png_image',
            field=models.ImageField(blank=True, upload_to='png_images/'),
        ),
    ]
