# Generated by Django 5.0.7 on 2024-10-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_url', models.URLField()),
                ('left_eye', models.ImageField(upload_to='left-eye/')),
                ('right_eye', models.ImageField(upload_to='right-eye/')),
            ],
        ),
        migrations.AlterField(
            model_name='avatar',
            name='sunglasses_image',
            field=models.URLField(),
        ),
    ]
